# Generated by Django 5.2.1 on 2025-06-17 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_assistent', '0001_initial'),
        ('chaos_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadContextEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_attribute', models.CharField(choices=[('information_short', 'Kurz'), ('information_long', 'Lang'), ('information_original', 'Original')], max_length=30)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaos_information.information')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_entries', to='chaos_assistent.thread')),
            ],
            options={
                'unique_together': {('thread', 'information')},
            },
        ),
    ]
