# Generated by Django 5.2.1 on 2025-06-17 01:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('daily_summary', models.TextField(blank=True, null=True)),
                ('positive_things', models.TextField(blank=True, null=True)),
                ('negative_things', models.TextField(blank=True, null=True)),
                ('daily_thoughts', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
