# Generated by Django 5.2.1 on 2025-05-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_information', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
