# Generated by Django 5.2.1 on 2025-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_information', '0002_delete_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='information',
            name='last_relevance_evaluation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='last_seen_by_agent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='last_seen_by_user',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='relevance_score',
            field=models.FloatField(default=1.0),
        ),
    ]
