# Generated by Django 5.2.1 on 2025-06-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Täglich'), ('WEEKLY', 'Wöchentlich'), ('MONTHLY', 'Monatlich'), ('YEARLY', 'Jährlich')], default='WEEKLY', help_text='Wie oft soll das Event wiederholt werden?', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Wiederhole alle `interval` Einheiten, z.B. alle 2 Wochen.')),
                ('by_weekday', models.CharField(blank=True, help_text='Nur bei WEEKLY: z.B. "MO,WE,FR".', max_length=20)),
                ('end_date', models.DateField(blank=True, help_text='Bis zu welchem Datum soll die Wiederholung laufen?', null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Täglich'), ('WEEKLY', 'Wöchentlich'), ('MONTHLY', 'Monatlich'), ('YEARLY', 'Jährlich')], default='WEEKLY', help_text='Wie oft soll das Event wiederholt werden?', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Wiederhole alle `interval` Einheiten, z.B. alle 2 Wochen.')),
                ('by_weekday', models.CharField(blank=True, help_text='Nur bei WEEKLY: z.B. "MO,WE,FR".', max_length=20)),
                ('end_date', models.DateField(blank=True, help_text='Bis zu welchem Datum soll die Wiederholung laufen?', null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='chaos_organizer.todo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
