# Generated by Django 5.2.1 on 2025-05-30 09:30

import chaos_documents.services.storage_backends
import chaos_documents.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUDIO_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=chaos_documents.services.storage_backends.DocumentMediaStorage(), upload_to=chaos_documents.utils.document_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CSV_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=chaos_documents.services.storage_backends.DocumentMediaStorage(), upload_to=chaos_documents.utils.document_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IMG_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, storage=chaos_documents.services.storage_backends.DocumentMediaStorage(), upload_to=chaos_documents.utils.document_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MARKDOWN_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=chaos_documents.services.storage_backends.DocumentMediaStorage(), upload_to=chaos_documents.utils.document_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDF_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=chaos_documents.services.storage_backends.DocumentMediaStorage(), upload_to=chaos_documents.utils.document_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TEXT_Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=chaos_documents.services.storage_backends.DocumentMediaStorage(), upload_to=chaos_documents.utils.document_upload_to)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
