# Generated by Django 5.2.1 on 2025-06-08 16:06

import chaos_documents.services.storage_backends
import chaos_documents.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('object_name', models.CharField(help_text='GCS object path', max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='markdown_document',
            name='markdown_image',
            field=models.ImageField(blank=True, null=True, storage=chaos_documents.services.storage_backends.DocumentMediaStorage(), upload_to=chaos_documents.utils.markdown_image_upload_to),
        ),
        migrations.AddField(
            model_name='markdown_document',
            name='embedded_assets',
            field=models.ManyToManyField(blank=True, to='chaos_documents.embeddedasset'),
        ),
    ]
