# Generated by Django 5.2.1 on 2025-06-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_documents', '0002_embeddedasset_markdown_document_markdown_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdown_document',
            name='embedded_assets',
        ),
        migrations.DeleteModel(
            name='EmbeddedAsset',
        ),
    ]
