# Generated by Django 5.2.1 on 2025-06-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_documents', '0004_embeddedasset_markdown_document_embedded_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdown_document',
            name='markdown_image',
        ),
    ]
