# Generated by Django 5.2.1 on 2025-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_documents', '0005_remove_markdown_document_markdown_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedasset',
            name='url',
            field=models.URLField(max_length=512, unique=True),
        ),
    ]
