# Generated by Django 5.2.1 on 2025-06-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_documents', '0006_alter_embeddedasset_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedasset',
            name='object_name',
            field=models.CharField(help_text='GCS object path', max_length=2048),
        ),
        migrations.AlterField(
            model_name='embeddedasset',
            name='url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
