# Generated by Django 5.2.1 on 2025-06-16 07:39

import chaos_documents.services.storage_backends
import chaos_documents.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_documents', '0007_alter_embeddedasset_object_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embeddedasset',
            name='url',
        ),
        migrations.AddField(
            model_name='embeddedasset',
            name='file',
            field=models.FileField(blank=True, null=True, storage=chaos_documents.services.storage_backends.DocumentMediaStorage(), upload_to=chaos_documents.utils.document_upload_to),
        ),
    ]
