# Generated by Django 5.2.1 on 2025-06-17 01:56

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(db_index=True, max_length=36)),
                ('vector', pgvector.django.vector.VectorField(dimensions=1536)),
                ('cluster_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [pgvector.django.indexes.IvfflatIndex(fields=['vector'], lists=100, name='embeddings_vector_ivfflat', opclasses=['vector_l2_ops'])],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
