# Generated by Django 5.2.1 on 2025-06-17 01:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('type', models.CharField(choices=[('KURZFRISTIG', 'Kurzfristig'), ('MITTELFRISTIG', 'Mittelfristig'), ('LANGFRISTIG', 'Langfristig')], max_length=32)),
                ('name', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('definition_description', models.TextField(blank=True, null=True)),
                ('definition_date', models.DateTimeField(auto_now_add=True)),
                ('definition_conditions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaos_mentor.goal')),
            ],
        ),
        migrations.CreateModel(
            name='GoalStatusUpdate',
            fields=[
                ('content', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaos_mentor.goal')),
            ],
        ),
    ]
